= POSTER

== Case Studies

WORLD MAP - with highlighted regions

- Thailand
- India
- Africa

== IMERG

IMERG shows the mesoscale spatial distribution of precipitation

Precipitation Distribution = Climate + Orography + Noise

Recurrent climate driven rain patterns function as a unique fingerprint for the precense of climate phenomena


ANNUAL MAPS OR RAIN

== PCA

Pattern extraction starts with a PCA of the 10 years of monthly IMERG records

High resolution mesocale data minimizes smearing, as patterns manifest all at once across the region with no apparant North/South or West/East onset delay.


PCA BASIS VECTORS

== PC subspace

Looking at IMERG records in the PC1/2 subspace show that climate is typically in on of two mutually exclusive positive or negative phases. This characteristic of most systems. Ex: ENSO, NAO, SAM, AO


Both EOF1 and EOF2 basis vectors always represent a mixture of both climate phases

Since both climate phases cannot cooccur, the subspace can be bifurcated into a positive and negative phase


Most recurrant patterns come in a positive and negative phase - ex: ENSO, NAO, SAM, AO


PC SUBSPACE REPROJECTIONS

== Climate Phase Basis

We can find each climate phase's pattern by finding the centroid of each half plane

This creates a pair of nonorthogonal rotated basis vector

== Climate Index

Doing an orthogonal projection on to these climate centroids we can calculate the presence of each climate phenomena and construct something akin to a local climate index.

To eliminate double counting each data point is projected onto the centroid of the half plane it's located on
