:imagesdir: fig/photo/eastern-caves/
:!webfonts:
:stylesheet: ../web/adoc.css
:table-caption!:
:reproducible:
:nofooter:


= Karst

Notes from *Karst Hydrology and Geomorphology* by _Derek Ford and Paul Williams_

== Carbonate Rocks
Vary along several dimensions

- limestone vs. dolomite
- carbonate vs silt/mud impurities
- calcite vs aragonite

=== Calcite/Aragonite
- Calcite is less dense
- Calcites 5 possible crystal structures which can combine in to a plethora of different configurations
- Aragonite just has one crystal structure
- Calcite can accomodate substitutions for *Ca^2+* in the its crystal structure. These are generally smaller  divalent cations (*Na^+*, *Mn^2+*, *Fe^2+*, *Zn^2+*, *Mg^2+*). Larger atoms (ex: *Sr^2+*)  don't integrate as easily
- Aragonite doesn't allow small cation substitution, but larger ones may be present (ex: *Sr* and *U*)
- Aragonite can invert to calcite. Since it's more dense this leads to a decrease in porosity
- If Aragonite dissolves and reprecipitates as calcite, it expells most *Sr* and *U* ions.

=== Dolomite

- Both a rock name (aka dolostone) and a mineral name
- Kinda like calcite but has one layer of *Ca^2+* cations alternating with a layer of *Mg^2+* cations. But for this you need a perfect 1:1 ratio of *Ca* to *Mg*. In reality you typically have a *Ca* rich ratio and *Ca* atoms in the *Mg* layer
- Zn Fe Mn Na Sr atoms can contaminate either layer
- Fe slots in particularly well in either layer - so you typically have more iron than in a calcite
- When it weathers the *Fe^2+* oxidizes to *Fe^3+*
- "As disorder increases so does solubility" (related to PCP??)
- "Staining with alizarin red is the standard means of distinguishing it from calcite (Adams et al. 1984)"
- Ca/Mg ratios can vary from rock to rock - and you're usually somewhere on a limestone/calcite vs dolomite spectrum. Don't expect it to be consistent!! (again, maybe different sources in the aquifer lead to a PCP signal) 

== Limestone deposition

- Coral reefs are not a major contributor by volume
- Mostly is precipitation of marine animal shells (ex: algae aragonite needles)
- Marine shells are then cemented and recrystallized
- Diagenesis can then lead to the formation of calcite spars (solid crystals of calcite.. like iceland spar
- River runoff can mix with the shell deposition creating calcareous shale/sandstone. So Limestone is often not very oure, Will have clay/mud/silicates/sand
- If there is little compaction and diagenesis you can get chalks
- Sometimes diagenese happens so slowly that you are left with the shapes of previous crystal structures or a ghost image of the original depositional environment (ex: biosparites)
- *Allochem* recognizable "grains" in carbonate rock
- Lithification preserved a tiny amount of organic material. About ~1% in modern limestone (page 15)
-  If the depositional environment is periodically exposed supratidaly then you can end up with layers of thing clay called *paleosol*.

- Terrestrial limestone forms at hotsprings - *tufa* (a framestone on root, plants, rocks around the spring) and *travertine* (crystalline, underground, inorganic)
- Calcium carbonate can also accu ulate a bit in lakes - *marls* - can form some sands

== Limestone Diagensis

- Limestone starts off as nuddy material at 40-80% porosity
- After diagensis it's about 5% porosity
- If its not buried deep and compacted then it remains porous and forms *chalk*.
- As the carbonate rock reaches above sea level, sea water is pushed out by meteoric water
- Rainwater leads to dissolution and the removal of aragonite [which is from the original shells I think!]
- Aragonite is then replaced with calcite spar
- If done slowly, retains aragonite crystal shape (ghosts)


- Dolimite probably occurs due to diagensis in lagoonal environmrnts bc it requires hypersaline environments
- It's likely formed by replacing earlier calcite/aragonite
- Another possibility is that fresh water intrusion creates conditions where calcite dissolved but dolomite does not (maybe in Florida right now)
- Geothermal activity may also play a role (page 21-22)
- *Breccia* broken fragments in a cement
- *Stylolites* = Pressure solution seam (very squiggly "bed"/layer). Forms below 500m (high pressure). It's dissolutional but concentrates impurities so is not very permiable (page 23). Can be along bedding planes but not always
- Silica may accumulate (for instance from sponges/radiolaria/diatoms) creating lenses of *chert* 
- At high pressure and heat youget annealing and formation of spars. At higher heat the crystals realign destroying fossiles and starting to form *marbles*

== Evaporation
- A little -> Dolomite (organic) - slightly above seawater salinity
- More -> Gypsum (inorganic) - 3x seawater strength
- A Lot -> Salt (inorganic) - 11x seawater strength
- Restricted evaporation lagoons - *sabkha*
- Gypsum when under pressure will turn to *anhydrite* and reduce by volume by 40%
== 
