#+TITLE: Limnology
#+DESCRIPTION:

#+INCLUDE: "../web/config.org"

#+PROPERTY: header-args :eval never-export :exports none

* Lake Archive Categories
** Lake Water
100s - 1000s of years at most\\
But in deep lakes this can be important. Typically more of an Ocean thing though
** Geomorphology/Shorelines 
1000s - 10 000s of years\\

*** Shorelines/Terraces 
Formed by wave action. They always form horizontally. Subsequent action (such as isostatic rebound or subsidence) may deform this horizontality

*** Geophysical 
The shape is gauged by seismic scan (explosion + microphones). Shapre tells you about the Lake Type (next section)
** Sediments
can outlive the lake itself..\\

Most sediment that gets washed into a lake will stay there - even if there is an outflow. The sedimentation rate is generally 1-2 orders of magnitude higher than in the oceans b/c of the catchment/water-body ratio (ex: Lake Baikal 0.3-6mm/year)

Retrieved by /coring/ or look at /outcrops/. Low bioturbation depths (mm-cm) + faster sedimentation = high resolution (ie. things get coverd up before they get too mixed)



* Types of lakes

- Genetic Lake Types :: Classifying lakes by how they were created
  + Tectonic Lakes :: divergence/convergence/transform/continental-collision
    - Rift Valley :: where plates separate. They're usually long and skinny and very deep. There is generally one steep "escarpment margin" and a more flat "felxural margin" based on the angle of the fault line. A failed rift, an /aulacogen/, then this lake will get presevered.
      + Lake Baikal :: 1.6km deep. 7km sediment. 25-30Myrs old
      + Lake Tanganyika :: Rift Valley lake. 14.km deep. Below 200m it's anoxic. Alkaline (sodium carbonate)
    - Lakes behind/front of volcanic ridges at subduction zones. Usually very large and shallow
      + Front :: *Peripheral* if the subduction zone is on dry land then the subduction point will make a basin
      + Back :: *Retroarc* The load of the acreted mountains at the subduction zone will weight the plate down and create a depression behind the mountain. These are huge (ex: /Black Sea/ / /Parathesis/)
    - Transtentional Basin :: kinks in strike/slip faults will lead to small spots where the plates effectively form a void/depression. ex: /Clear Lake/, /Ridge Basin/ (Link&Osborn 1978) (Hearn et al. 1988)
    - Continent-Continent collision :: this leads to general plate chaos and you get lot of microplates and transtentional basins and whatnot (ex: Lakes in Mongolia bc of Himalaya)
  + Cratonic lakes :: are in middle of continents where the continent has gone over some non-uniformity in the mantle. Generally quite shallow. Formation is a bit unclear.
  + Volcanic Lakes ::  (same as Maar lakes?) Crater lakes. Explosively created lakes. Steep sides, no/low inflow. 
    - Maars :: One sudden explosion. Magma hits some water. Circular. In Indonesia too.. (need to find ref). And on Titan! where during cool periods methane builds up in the ground and then explodes
    - Crater Lakes :: very deep, steep sides -> wind sheltering -> no wind mixing -> anoxic bottoms (ie. good preservation). Volcanic domes can form  islands. And the caldera can suddenly collapse leading to  catastrophic drainage (ex: Aniakshak Alaska). Re-eruptions ruin the limnology (ex: Lake Toba)
    - Limnic eruptions :: Build up of dissolved CO_{2} under water (where it is under a lot of water pressure and dissolvable). Once it comes out of solution, the water starts to mix and the CO_{2} comes up to a level where it can come out of solution all at once (with a positive feedback driving the mixing) - ex: Lake Nyos
  + Landslide Lakes :: like what we have in Taiwan (TODO: Find which one it is)
  + Glacial Lakes  :: Can both be host to very slow deposition (varves) and catastrophic deposition (ice dam burst, glacial till etc.)
    - Ice lakes :: Lakes in contact with a glacier or on a glacier.
    - Glacial rock basins :: ie. carved glaciers.. cirque lakes, piedmon,fjord etc..
    - Morainic/outwash lakes :: formed at the terminal point of ice advance
    - Drift basins :: kettle lakes (blocks of ice/permafrost left behind - periglacial lakes), thermokarst (TODO: What is this..?)
  + Karst lakes :: ex: sinkholes - washed out karst holes
  + Fluvial Lakes :: River generated. 8% of total lakes (and 0.3% of volume - b/c shallow and numerous)
    - Plunge pool :: under a waterfall.. 
    - Oxbow lakes :: caused by rivers meandering and cutting of their own flow along bends.  
    - Rivers blocks :: each other when the flow rate suddenly changes and there is a huge inflow of sediment down one channel (ex: Tulare Basin). 
    - Anastomosing rivers :: due to drastic changes in river level and sediment material, you can get a flood plain with lakes
  + Aeolian Lakes :: caused by wind (called /deflation/), either an eroded basin or dammed outlet (ex: Qattara Depression in Egypt)
  + Shoreline Lakes :: tombolo lakes, spits lakes, created by ocean currents bringing material (TODO: Look into). These are typically not very old.
  + Organic lakes :: beavers, corals etc created lakes
  + Anthropogenic Lakes ::
  + Meteorite Lakes ::
  + Solution Lakes :: Something is dissolving..  ex: karst in Dalmatian coast. Dedolomitization caused by gypsum dissolution (Bischoff et al. 1994). Fresh water mixing with salt water can accelerate karstification (Upchurch & Randazzo 1997) - so fluctuations in sea level can exacerbate things. Brenner 1994 "Lake Salpeten and Quexil"
  + Saline Lake :: brine pools.. groundwater inflow and outflow. Mud flats fed from below. Lake margins that move a lot between seasons
  + Meteoric Lakes :: tiny watersheds - last millions of years (steep sides like volcanics). ex: Lake Bosumtwi Ghana  


- Trophic Lakes Types :: "Trophic, from Ancient Greek τροφικός (trophikos) "pertaining to food or nourishment", may refer to" - Wiki. We divide lakes based on 2 paramters - the *allochthonous* source of nutrients (coming from outside into the lake) and *autochthous* (coming from within)
  + Oligotrophic
  + Eutrophic
  + Dystrophic

The fast majority of lakes are glacial and at higher latitudes    
* Lake Zones

- Shoreline :: The shoreline is a great paleoclimate record, however it can change severly due to tectonic motion. Primarily by isostatic rebound after glacial withdrawl. This can great complicate your analysis b/c shore lines may be irregularly lifted relative to their original positions
- Photic Zone :: area of photosynthesis
- Aphotic Zone ::
- Benthic :: lake floor
  + Littoral :: photic zone of the floor
  + Sublittoral :: photic but only by algae/cyanobacteria (not *macrophytes* - large submerged plants)

All zones are species dependent (due to different light absorption spectra and light's interaction with turbidity)

* Mixing and Stratification

Fluid with either flow *laminarly* or *turbulently* according to the following relationship:
#+begin_quote
*Reynolds Number*

R_{e} = U L \rho{} / mu{}

- U :: velocity of flow
- L :: reference length
- \rho{} :: fluid density
- \mu{} :: viscous forces
#+end_quote
/R_{e} < 500/ = laminar
/R_{e} > 2000/ = turbulent

Bear in mind that cold water will generally be more viscous - and water mixed with sediment will also be viscous and will sometimes flow laminarly.

*Turbulent mixing* occurs when adjacent bodies of water are moving at different speeds and they have similar densities

#+begin_quote
*Richardson's number*

R_{i} = g (p\rho{}/dz)/\rho{}(du/dz)^{2}

- g :: gravitation constant
- \rho{} :: density
- z :: depth
- u :: velocity
#+end_quote
If *R_{i}* < 0.25 then mixing occurs, otherwise *stratification* - with the lower layer called the *hypolimnion* and the higher/upper layer called the *epilimnion*. The in-between zone will be called the *metalimnion* and it will contain the *thermocline* - the depth at which you have the highest temperature gradient.

This paramterization may be sufficient on a micro level - but is not directly applicable when characterizing a lake. For that we develop a new metric that is in terms of known/measurable lake paramters


#+begin_quote
*Stratification index*

S = \mu{}^{3}\rho{}C_{\rho{}} / z g \alpha{} (Q_{0} - 2 Q_{1} / c z)

- \mu{} :: fristional velocity of air
- \rho{} :: density of water
- C_{\rho{}} :: specific heat of water at constant pressure
- z :: water depth
- g :: gravational constant
- \alpha{} :: coefficient of thermal expansion
- Q_{0} :: net surface heat input
- Q_{1} :: solar radiation penetrating water column
- c :: extinction coefficient
#+end_quote
A well mixed water mass will stratify when *S* drop below ~6700.

Stratification is quasi-stable. While a mixing body of water will stratify when conditions are met, transitioning from a stratified state to a mixing state requires an additional input of energy. If the lake system is vasillating around /S = 6700/ it will not rapidly switch between mixing and stratification. It will stratify and then "stick"The energy to change to a mixing state is characterized by the lake's *stability*

#+begin_quote
*Wedderburn number*

W = [(\rho{}_{2} - \rho{}_{1})/\rho{}) / \rho{}] g h^{2} / \mu{}^{2}L

- \rho{}_{2} :: density of hypolimnion
- \rho{}_{1} :: density of epilimnion
- \rho{} :: density of water
- h :: depth of epilimnion (TODO: look into parameter)
- \mu{} :: shear velocity in the water at the water surface (TODO: What..? probably wind speed related)
- L :: length of lake in the wind direction - ie. the *fetch*
#+end_quote

If /W > L/4h/ then stratification is strong and mixing is inhibited. Generally a large thermal contrast will lead to large density difference and make the stratification more stable

Notice that temperature/energy is also characteristic of the /Stratification Index/. Both values co-vary, but the stability is also a function of the wind and lake length. The wind/fetch (and therefore geometry of the lake vs. prevailing wind direction) will also affect the depth of the thermocline

#+begin_quote
D_{th} = 4F^{0.5}

- D_{th} :: depth of thermocline (m)
- F :: maximum fetch (km)
#+end_quote

This equation must be a very rough approximation since it doesn't factor in variables like turbidity. But the point is that the depth of the thermocline is also an indicator of stability

** Regional differences

High latitude lakes experience large seasonal temperature variations. However the density of water does not change a lot at low temperatures - so large fluctations of cold waters don't create necessarily create a large density contrast.

At tropical latitudes you have more favorable temperatures but the temperature fluctuations are small

So there is a sweet spot (local maximum of sorts) at around 20\deg{}-30\deg{}

** Lake mixing types

Obviously the seasons are the strongest driver for lake mixing. As a result there are several classes of lakes:

- Dimictic Lake :: is one that completely mixes twice annually. One during the winter when ice forms (and there is no wind) and once in the summer when you have a strong temperature contrast. The /complete/ part is essential b/c it allows the bottom to be ventilated, critters can live on the lake floor, you get bioturbation and a very different sedimentary record.
- Monomictic Lake :: One mix..
  + Warm version :: typically it's like a dimictic, but since the winter doesn't get cold enough to create an ice cap, mixing next stops in the winter. So you have one long mixing season
  + Cold version :: like the dimictic, but the summer never gets warm enough to stratify..
- Meromictic Lake :: is one with only partial mixing. The bottom will have no bioturbation and you will get fine laminations in your sediment. So you can easily observe seasonality is runoff/nutrients/biological activity in higher mixing layers
  + mixolimnion :: the mixing upper water mass
  + monimolimnion :: the poorly mixing bottom mass
  + endogenic meromixis :: salts released from organic decay at the bottom
  + ecotgenic meromixis :: externally input salts (both are salty dense bottom water with light fresh water on top)
- Polymictic Lake :: mixes repeatedly. Usually small lakes that are easily disturbed by strong winds. Or arid lakes where evaporative cooling plays a major role
- Oligomictic Lake :: rarely/irregularly mixes. Usually also wind driven..
- Amictic lake :: never mix (ex: always covered by ice)

* Waves
Will either be *progressive* (moving forward) or *standing*. They have the following parameters

- Wavelength :: \lambda{}
- Height :: h
- Period :: T
- "Orbitals" :: the motion vertically of the water particles
- Deep-water wave velocity :: For waves below the surface, the speed will be /\lambda{}/T/
- Shallow water waves :: if /\lambda{}/2 > z/ then the wave is squeezed in by the lake floor. The wave will start to move sediment. And the velocity will be dictated by /u = \pi{}HT sin (z 2\pi{}z/\lambda{})/ (
#+begin_quote
- TODO: Check this equation.. it doesn't make sense)
#+end_quote
The variable flow in these shallow waves can result in heavy particles moving landward and finer particles moving lakeward. Maybe more details in .. Komar and Miller, 1975 (???)

Since the wave is not typically orthogonal to the shore, as it approaches it gets squeezed, the wave refracts towards the coast, and a coastal *longshore current* is formed (as fast as 30cm/s) - se Freeman et al. 1972, Sly 1978. These leave *ripples* and *sand bars*. In even a large lake, this zone is only a few meters wide

Waves break when wave steepness is >1/7

- Seiches :: standing waves along the length of the whole lake. Typically due to constant wind action. This will also distort the thermocline (sharper downwind). The pilling up on water downwind can cause backflow below - and in effect an overturn of the whole water body

- Poincare waves :: oscillatory cells in the middle of large lakes due to the Coriolis effect

- Kelvin waves :: shoreline-parallel waves due to Coriolis. (Saggio and Imberger 1998)

* Currents

Generally not a huge factor in lakes.. for obvious reasons. In small lakes this is dominated by inflow/outflow, which in turn is dominated by seasonality. River water will flow into the lake and flow down till it reaches a level of similar density - and then it'll flow "into" the lake

- overflow :: the river water floats above the lake - creating a lid. Usually with low sediment; often fresh water flowing over salty
- interflow :: mixes somewhere in the middle. Usually this is in statified lakes. The downward flow will naturally cause turbulence and mixing. This can be greatly affected by Coriolis - which will dictate where nutrients get distributed in the lake [2-15 cm/s]
- underflow :: along the bottom.. usually inflow with lots of sediment. Can reach high speeds and move sands [100 cm/s] Grover and Howard 1938, Pickrill and Irwin 1982, Lambert 1982 Wierich 1984
- gravity flow :: very sediment heavy underflow. Like due to earthquakes/landslides. If it's an "event" it can also be called a *turbidity flow* which has a *head* *body* and *end*. These can even be erosive and create channels. On the bottom they will form a *sublacustrine fan*.
  
Of course this can all change seasonally - and leave a paleorecord!

* Sediment
Classification is complicated a bit b/c it's quite multidimensional and you can't pigeon hole sediments easily:

** Controls
The controls on sidment are as follows:
- Eustasy :: lake/sea level
- Subsidence ::
- Sediment supply ::
- Basin morphology ::
- Sediment compaction ::
- Flexural isostasy :: Seems like it's similar to isostatic rebound??

** Loss on Ignition
A metric of "organic content" - *IG*

** Trophic Level
A gauge of the biological activity of a lake based on the ratio of *minerogenic* matter /Si/- *inorganic biogenic material*  (diatome fustules and biogenic precipitated calcium carbonate /D-group/

From /Si/ to /D/ there are classified as (nutrient poor) *oligotrophic*, *mesotrophic* and *eutrophic* (nutrient rich)

** Humic Level
This is another gauage of biologcal activity but on the *C/N* ratio.

This ranges from *dystropic/polyhumic* (~C/N = 10-15~) to *oligohumic* (~C/N < 10~)

** BPI/BPN

Nitrogen content /N/ generally correlates with organic content /IG/. How much the two co-vary is summarized using two different measures.
- BPN :: /bioproduction number/ which is is the "slope" of the N = f(IG) line.
- BPI :: /bioproduction index/ - which is the /N/ content at 10% /IG/.
Both say the same thing though..

Using this these values (ie. the N/IG ratio) we can say something about a lake's Trophic/Humic levels. At low /IG/ and /N/ values we can primarily infer the humicity (the /C/N/ ratio will be high) - while at high IG and N values we can infer about the lake's trophic level (high /IG/ would imply a lot of biogenic-precipitates//D-group/

ge0k0n


** Geochemical Classification
- oxic/anoxic ::
  + sulfidic :: measurable dissolved sulfide : /S^{2-}/ 
  + non-sulfidic :: can be divided further into.. :
    - post-oxic :: "oxygen removal without sulfate reduction" (TODO: doesn't that make it sulfidic??)
    - methanic :: complete sulfate reduction and methane gas formation
#+begin_quote
These seem incorrect. Post-oxic should be a "sulfidic"
#+end_quote
Diagenesis often proceeds along the sequence of : ~oxic -> post-oxic -> sulfidic -> methanic~

** Genetic Classification
Main 3: Lithogenous / Biogenous (carbonate) / Hydrogenous

Others; Evaporite / Organic sediments (carbon based) / Iron-rich sediments / Sulfuric sediments

** Mechanical Classification


Using a "cone apparatus" *Wentworth Scale* or *Phi Scale*
ex: Rock/boulder - pebbles/mussles - gravel/sand - sand - sandy silt - hard clay - fine sediments - very fine sediments


2. Sphericity/Elongated :: brought by river -> round

Roundness/Texture
* Lake Evolution
Lake -> Marsh -> Floating Fen -> Basin Fen -> Valley Bog -> Raised Bog

Caused by the water slowly filling in with Peat/Turf. This is partially decayed vegetation or organic matter (ex: Sphagnum Mosses)
* Chemistry
** Oxygen
Redox reactions .. ex: organic stuff -> /CO_{2}/. A lot of this is happening on the lake floor and it's Very tied to stratification and turn over in the Lake. 

It also dissolves worse in water when the water is warmer. Summer statification and high temperatures can lead to very low oxygen levels and kill a lot of animals (*summerkill*). As you go deeper the water will be colder - but then since you have minimal mixing it will have less oxygen reaching it. Somewhere in the middle is the *metalimnetic oxygen maximum*.

It will also change a lot througout the day due to photosynthesis. Especially is the lake is eutrophics (nutrient rich)

Production is primarily dictated by lake surface area - however consumption is dictated by lake bed surface area. So the lake basin's shape and subsequent changes in lake level can greatly alter oxygen consumption and production.

** Iron
In very anoxic conditions, /Fe^{3+}/ will turn to /Fe^{2+}/ and this can dissolve into the water. The anoxic zone needs to be relatively thick b/c once /Fe^{2+}/ hits any oxic layer it'll turn back into Fe^{3+}. 

** Carbon
CO_{2} is an important form of carbon that makes water acidic

Redfield ration /C/:/N/:/P/ = /106:16:1/ - "ideal" nutrient ration for phytoplankton. Usually an insufficient amount of one stalls the development of more organic life.

** Nitrogen
Necessary for life (ex: nucleotide - Guanine)

Inert as /N_{2}/. To be bioavailale it needs to be "fixed" by something like cyanobacteria. So when it's bioavailable form is insufficient then the fixers have a distinct advantage vs. other organisms.

/\shy{}^{15}N/ is an isotope that's enriched at each trophic level by about /3-4%/

The *C/N ratio* can tell you about past plant types. Terrestrial plants have lots of cellulose and therefore lots of /C/ and low /N/. Phytoplankton by contrast have lower C/N ratios. Combined with /\shy^{13}/ you can ID the organic matter types.

** Phosphorus
DAN/RNA/ATP/Phospholipids

all isotopes are radioactive ..

Recycles easily, so not a great paleorecord

** Silica
has isotopes..

is what diatoms use

Lots of lil skeletons.. everywhere.. all the time (can look at species compositions I guess?)

* Determining Sediment Age
- Relative ages :: by looking at what layers deposited above other.  Sometimes layers can be disturbed to the point where this gives wrong or deceptive results.
- Absolute ages :: You use some radioisotope or whatever to get an actual age directly

Obviously it's best if you can use the two in combination..

- Chronology :: arranging events/dates in order of occurrence

- Chronometry :: Measuring the dates.. like with radioisotopes

- Radioisotopes :: Radiocarbon / /\shy{}^{230}Th/ / /\shy{}^{210}Pb/

- Radiation damage :: Radioactive decay damages crystal structures. This builds up some strain in crystals which can be released as luminescence

- Amino acid racemization :: amino acids (>500 in total, but 20 are used in genetic code) will spontaneously change chirality over time (temperature dependent). So it can function as a clock of sorts.

- \shy{}^{14}C :: Cosmic Rays -> spallation -> \shy{}^{14}N => \shy{}^{14} + thermal neutron => \shy{}^{14}CO_{2}

- \shy{}^[13}C :: ~1%

- /\shy{}^{210}Pb/ :: from /\shy{}^{222}Rn/ that's in the air .. so lead raining everywhere all the time.. can determine sedimentation rates and all that jazz. Super cool. Does it end up in stalagmites..? Prolly.. should check


* Biomarkers
- Pollen :: plankton size
- Rotifers :: small animals
- Crustaceans :: 
- Ostracodes :: bivalve bean shaped things.. with calcareous shells
- Insects :: ex: Chironomids leave behind hard mouth parts
- Fish :: Nektons (active swimming animals in water - vs. planktons). Leave behind scales and ear pieces: *Otolith*
- Ancient DNA :: spooky stuff...
** Phytoplankton
Som are photoplankton some are heterotrophic
- Blue/green algae :: ie. Cyanobacteria. Nitrogen fixers (using their /heterocysts/). Thrive in places with nitrogen runoff (Baltic Sea)
- Dinoflagellates :: Eukaryotes with two flagella. Their resting cyst is what gets typically preserved. They cause red tides
- Diatoms :: Made up of two siliceous frustules (like a box). However frustules easily dissolve in high pH
- Gold brown algae (Chrysophytes) :: often with falgella .. some have siliceous scales. Also have cysts that get preserved
- Green Algae (Chlorophytes) :: unicellular and collonial. Many don't get preserved at all.. Some have carbonate parts - like the "stoneworts" Charophytes
- Charophytes :: freshwater green algae that create spirals. Different species prefer different conditions.
  
